### ISSUE TITLE
Failed to download bugs

### ISSUE THREAD

**Issue by Mannivu** [ChristopherGittner/OSMBugs#19]
If I try to load Osmose and Mapdust bugs I get an error saying "Failed to download from Osmose" and "Failed to download from Mapdust".

**Comment by ChristopherGittner** [comment]
Hi Mannivu,

i released a new Version that has a longer timeout for Osmose requests (40 seconds).
Some requests seem to take a very long time and the default timeout was too short.

Unfortunately i was not able to reproduce the "Failed to download from Mapdust" error.
Please try the new version (It will take some time to be available at the Play Store and some more time to appear on F-Droid) and tell me if the error still applies to you.
If the error persists, please tell me which options you had enabled for Mapdust, and maybe make a screenshot from the map, when the Error occured. This helps me to reproduce the bug.

**Comment by Mannivu** [comment]
Unfortunately the issue persists even after the update. I attach the screenshots of both the Mapdust options enabled and of the map.
![Screenshot_2019-05-12-10-14-50-082_org gittner osmbugs](https://user-images.githubusercontent.com/42747216/57715365-dbf51000-7676-11e9-83da-2ed64de39b51.png)

![Screenshot_2019-05-14-18-26-22-263_org gittner osmbugs (1)](https://user-images.githubusercontent.com/42747216/57715139-48234400-7676-11e9-8b8c-9345338483aa.png)

**Comment by ChristopherGittner** [comment]
Hi Mannivu,

can you please try the current Version and test if the Mapdust error still persists?

See Issue @ #22 where maybe the same error applied.

**Comment by Mannivu** [comment]
I've just downloaded version 1-2-1 from PlayStore and both Mapdust and Osmose works. Thank you.
